Zadanie JDP220301-22
piotr-grosicki/project-jdp-2203-01 pull request #24
Opened 2022-03-18 14:23 UTC by michalszmit

2022-03-18 18:43 UTC, MJKPW requested changes

2022-03-18 18:43 UTC, MJKPW commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto getGroup(@RequestParam Long id) throws GroupNotFoundException {
Wydaje mi się, że powinniśmy się trzymać jednej wersji i używać wszędzie PathVariable.

2022-03-18 19:37 UTC, MJKPW commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<Long> productIds;
Wydaje mi się też, że ta lista nic nie robi.

2022-03-18 19:41 UTC, MJKPW reviewed
Musimy też się chyba zdecydować jak pisać ścieżki. Ja nazywałem w stylu snake_case u Ciebie jest CamelCasem.

2022-03-18 22:26 UTC, KatarzynaNabozny commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto getGroup(@RequestParam Long id) throws GroupNotFoundException {
Masz rację, trzeba to zapisać na grupie, żeby sobie każdy sprawdził jak ma, bo potem może być problem.

2022-03-18 22:27 UTC, KatarzynaNabozny commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<Long> productIds;
Ona nic nie robi bo powinna być uzupełniona w mapperze. Tak mi się przynajmniej wydaje.

2022-03-19 00:19 UTC, KatarzynaNabozny commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> -@CrossOrigin("*")
Wydaje mi sie, że ta adnotacja musi tu być i nie wolno jej usuwać. Przynajmniej jak  ja jej nie miałam w zadaniu ,już nie pamietam z jakiego dokładnie zadania w kursie to wyskakiwał mi błąd CrossPolicy

2022-03-19 00:33 UTC, MJKPW commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> -@CrossOrigin("*")
Z tego co pamiętam to związana jest chyba z frontendem.

2022-03-19 16:32 UTC, michalszmit commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto getGroup(@RequestParam Long id) throws GroupNotFoundException {
Cześć 
Ścieżka zmieniona na @PathVariable

2022-03-19 16:34 UTC, michalszmit commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<Long> productIds;
Usunąłem finalnie tę listę. 
Miałem problem z jej zmapowaniem, jakieś dziwne błędy mi się pojawiały w mapperze i projekt odmawiał budowania

2022-03-19 16:34 UTC, michalszmit commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> -@CrossOrigin("*")
Dodana adnotacja @CrossOrigina("*")

2022-03-19 20:02 UTC, EredinSH commented
Moim zdaniem jest ok. Daję approve

2022-03-19 20:02 UTC, EredinSH approved these changes

2022-03-19 20:44 UTC, MJKPW approved these changes

2022-03-19 20:45 UTC, robertSliwinski1979 approved these changes
lombok i konstruktor, IntelliJ to bystry program, na pewno coś sobie wybierze. Daje approva

2022-03-19 20:45 UTC, robertSliwinski1979 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    public GroupDto(Long id, String name) {
Uważam , że (ale mogę się mylić -> za co sorki) w konstruktorze numer ID jest przydzielany automatycznie (kiedy tworzyliśmy bazę danych ->autoincrement), czyli jego się nie wpisuje ręcznie, baza danych robi to za nas. Poza tym użyłeś adnotacji @AllArgsConstructor i tworzysz konstruktor -> czyli albo jedno albo drugie

2022-03-19 20:45 UTC, robertSliwinski1979 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> -@AllArgsConstructor
Uważam , że (ale mogę się mylić -> za co sorki) w konstruktorze numer ID jest przydzielany automatycznie (kiedy tworzyliśmy bazę danych ->autoincrement), czyli jego się nie wpisuje ręcznie, baza danych robi to za nas. Poza tym użyłeś adnotacji @AllArgsConstructor i tworzysz konstruktor -> czyli albo jedno albo drugie

2022-03-19 23:30 UTC, merged