User entity implementation
piotr-grosicki/project-jdp-2203-01 pull request #4
Opened 2022-03-02 02:20 UTC by MJKPW

2022-03-02 07:41 UTC, piotr-grosicki requested changes

2022-03-02 07:41 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +public class Order {
w tym zadaniu nie powinna powstac encja orders. tylko user i niezbedne wydmuszki (tylko z id)

2022-03-04 18:34 UTC, piotr-grosicki requested changes

2022-03-04 18:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dao/CartDao.java
> +public interface CartDao extends CrudRepository<Cart, Long> {}
cart dao nie powinno powstac w tym zadaniu

2022-03-04 18:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dao/OrderDao.java
> +public interface OrderDao extends CrudRepository<Order, Long> {}
order dao nie powinno powstac w tym zadaniu

2022-03-05 14:12 UTC, piotr-grosicki approved these changes

2022-03-06 22:40 UTC, KatarzynaNabozny commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Long id;
Proponuje zastosować LOMBOKA I adnotacje nad polami, tak jak ustaliliśmy:)

2022-03-06 22:50 UTC, KatarzynaNabozny reviewed
**Dodać Lomboka** i usunąć Dao

2022-03-07 15:31 UTC, EredinSH approved these changes

2022-03-07 17:48 UTC, merged